# Generated by Django 5.0.2 on 2024-02-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='username',
            field=models.CharField(default='ethan', max_length=125),
            preserve_default=False,
        ),
    ]
