# Generated by Django 5.0.2 on 2024-02-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
