# Generated by Django 5.0.2 on 2024-02-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_idea_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='favorited',
            field=models.BooleanField(default=False),
        ),
    ]
