
name: Deploy to Server

on:
  push:
    branches:
      - master  # Triggers the workflow on push events to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

    - name: Copy Code to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./"
        target: "/home/ethand320/deployment/FanPulse/"
      # Copies the repository files to your server

    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ethand320/deployment/citemed-ai/
#          docker build -t citemed-ai .
#          docker stop citemed-ai || true
#          docker rm citemed-ai || true
#          docker run -d --name citemed-ai -p 5001:5001 citemed-ai
      # SSH into your server, build the Docker image, and run it